export const FETCH_COURSES_START = "FETCH_COURSES_START"
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS"
export const FETCH_COURSES_ERROR = "FETCH_COURSES_ERROR"
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS"
export const JOIN_COURSE_SUCCESS = "JOIN_COURSE_SUCCESS"
export const FETCH_TASKS = "FETCH_TASKS"
export const FETCH_TASK = "FETCH_TASK"
export const FETCH_TASK_START = "FETCH_TASK_START"
export const COURSES_RESET_ERROR = "COURSES_RESET_ERROR"
export const COURSES_RESET_COURSE = "COURSES_RESET_COURSE"
export const COURSES_RESET_COURSES = "COURSES_RESET_COURSES"
export const COURSES_ADD_NEW_COURSE = "COURSES_ADD_NEW_COURSE"
export const COURSE_UPDATE_MEETING = "COURSE_UPDATE_MEETING"
export const FETCH_MEETING_START = "FETCH_MEETING_START"
export const FETCH_MEETING_END = "FETCH_MEETING_END"
export const SET_GRADE_MEETING = "SET_GRADE_MEETING"
export const GRADE_MEETING_START = "GRADE_MEETING_START"
export const GRADE_MEETING_SUCCESS = "GRADE_MEETING_SUCCESS"
export const SET_COURSE_MEETINGS = "SET_COURSE_MEETINGS"
export const SET_COURSE_MEETING = "SET_COURSE_MEETING"
export const RESET_COURSE_MEETING = "RESET_COURSE_MEETING"
export const SET_COURSE_AUTH_ERROR = "SET_COURSE_AUTH_ERROR"
export const RESET_COURSE_AUTH_ERROR = "RESET_COURSE_AUTH_ERROR"


export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_ERROR = "SIGNIN_ERROR"
export const RESET_SIGNIN_ERROR = "RESET_SIGNIN_ERROR"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_SET_READY_STAGE = "AUTH_SET_READY_STAGE"
export const AUTH_RESET_REDIRECT = "AUTH_RESET_REDIRECT"
export const AUTH_RESET_REDIRECT_TO = "AUTH_RESET_REDIRECT_TO"
export const AUTH_SET_REDIRECT_TO = "AUTH_SET_REDIRECT_TO"
export const AUTH_SET_VK = "AUTH_SET_VK"
export const AUTH_SET_VK_SESSION = "AUTH_SET_VK_SESSION"
export const AUTH_ACTIVE_REDIRECT = "AUTH_ACTIVE_REDIRECT"
export const AUTH_SET_LACK_OF_USERNAME = "AUTH_SET_LACK_OF_USERNAME"
export const AUTH_RESET_LACK_OF_USERNAME = "AUTH_RESET_LACK_OF_USERNAME"



export const COURSES_RESET_REDIRECT = "COURSES_RESET_REDIRECT"


export const SEND_HOMEWORK_START = "SEND_HOMEWORK_START"
export const SEND_HOMEWORK_SUCCESS = "SEND_HOMEWORK_SUCCESS"
export const SEND_HOMEWORK_ERROR = "SEND_HOMEWORK_ERROR"

export const ERROR_SET = "ERROR_SET"
export const ERROR_RESET = "ERROR_RESET"

export const HOMEWORK_COURSE_ID = "HOMEWORK_COURSE_ID"
export const HOMEWORK_USER_STATUS = "HOMEWORK_USER_STATUS"
export const HOMEWORK_SET = "HOMEWORK_SET"
export const HOMEWORK_RESET = "HOMEWORK_RESET"
export const HOMEWORK_OVER = "HOMEWORK_OVER"

export const RESET_TASK = "RESET_TASK"
export const FETCH_TASK_ERROR = "FETCH_TASK_ERROR"
export const RESET_FETCH_TASK_ERROR = "RESET_FETCH_TASK_ERROR"
export const SET_TASK_SUCCESS = "SET_TASK_SUCCESS"
export const SET_TASK_START = "SET_TASK_START"


export const TEST_MESSAGE_SUCCESS = "TEST_MESSAGE_SUCCESS"
export const TEST_MESSAGE_FAIL = "TEST_MESSAGE_FAIL"

export const SET_COURSE_STATS = "SET_COURSE_STATS"
export const RESET_COURSE_STATS = "SET_COURSE_STATS"

//MEETING
export const FETCH_MEETING = "FETCH_MEETING"
export const FETCH_MEETING_ERROR = "FETCH_MEETING_ERROR"
export const RESET_MEETING_ERROR = "RESET_MEETING_ERROR"
export const FETCH_MEETING_ATTENDANCE = "FETCH_MEETING_ATTENDANCE"
export const RESET_MEETING = "RESET_MEETING"
export const MEETING_SET_ERROR = "MEETING_SET_ERROR"



