export const FETCH_COURSES_START = "FETCH_COURSES_START"
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS"
export const FETCH_COURSES_ERROR = "FETCH_COURSES_ERROR"
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS"
export const JOIN_COURSE_SUCCESS = "JOIN_COURSE_SUCCESS"
export const FETCH_TASKS = "FETCH_TASKS"
export const FETCH_TASK = "FETCH_TASK"
export const FETCH_TASK_START = "FETCH_TASK_START"
export const COURSES_RESET_ERROR = "COURSES_RESET_ERROR"
export const COURSES_RESET_COURSE = "COURSES_RESET_COURSE"
export const COURSES_ADD_NEW_COURSE = "COURSES_ADD_NEW_COURSE"
export const COURSE_UPDATE_MEETING = "COURSE_UPDATE_MEETING"
export const FETCH_MEETING_START = "FETCH_MEETING_START"

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_ERROR = "SIGNIN_ERROR"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_SET_READY_STAGE = "AUTH_SET_READY_STAGE"


export const AUTH_RESET_REDIRECT = "AUTH_RESET_REDIRECT"
export const COURSES_RESET_REDIRECT = "COURSES_RESET_REDIRECT"
export const COURSES_RESET_TASK = "COURSES_RESET_TASK"

export const SEND_HOMEWORK_START = "SEND_HOMEWORK_START"
export const SEND_HOMEWORK_SUCCESS = "SEND_HOMEWORK_SUCCESS"
export const SEND_HOMEWORK_ERROR = "SEND_HOMEWORK_ERROR"

export const ERROR_SET = "ERROR_SET"
export const ERROR_RESET = "ERROR_RESET"

export const HOMEWORK_COURSE_ID = "HOMEWORK_COURSE_ID"
export const HOMEWORK_USER_STATUS = "HOMEWORK_USER_STATUS"
export const HOMEWORK_SET = "HOMEWORK_SET"
export const HOMEWORK_RESET = "HOMEWORK_RESET"
export const HOMEWORK_OVER = "HOMEWORK_OVER"

